# Generated by Django 2.2.6 on 2019-10-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaveRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=-1)),
                ('date', models.DateTimeField(verbose_name='Date the rating was made')),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
